# Generated by Django 2.2 on 2021-12-29 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('status', models.CharField(default='Incomplete', max_length=10)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('scraped_date', models.DateField(blank=True, null=True)),
                ('neighbours', models.ManyToManyField(blank=True, null=True, to='clusters.URL')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_url', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('scraped_date', models.DateField(blank=True, null=True)),
                ('cluster', models.ManyToManyField(null=True, to='clusters.Cluster')),
                ('url', models.ManyToManyField(null=True, to='clusters.URL')),
            ],
        ),
    ]
