# Generated by Django 2.2 on 2021-12-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='neighbours',
            field=models.ManyToManyField(blank=True, null=True, related_name='_url_neighbours_+', to='clusters.URL'),
        ),
    ]
