# Generated by Django 2.2 on 2021-11-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='text_data',
        ),
    ]
