# Generated by Django 2.2 on 2021-12-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_auto_20211229_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='neighbours',
            field=models.ManyToManyField(blank=True, null=True, to='clusters.URL'),
        ),
    ]
