# Generated by Django 2.2 on 2021-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_auto_20211229_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='cluster',
        ),
        migrations.AddField(
            model_name='cluster',
            name='data',
            field=models.ManyToManyField(null=True, to='clusters.Data'),
        ),
    ]
