# Generated by Django 2.2 on 2021-11-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_remove_url_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
